<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot\js\Legacy.js" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\js\Legacy.js" />
    <None Include="wwwroot\js\Criaturas.js" />
    <None Include="wwwroot\js\WorldPlayer.js" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="jQuery" Version="3.7.1" />
    <PackageReference Include="jTable" Version="2.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TibiaLegacyBusiness\TibiaLegacyBusiness.csproj" />
  </ItemGroup>

</Project>
